-- Analytics Copilot: Snowflake Environment Setup
-- Run this as SYSADMIN (or ACCOUNTADMIN for warehouse creation)

-- 1. Warehouse
CREATE WAREHOUSE IF NOT EXISTS COPILOT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- 2. Database
CREATE DATABASE IF NOT EXISTS ANALYTICS_COPILOT;

-- 3. Schemas
USE DATABASE ANALYTICS_COPILOT;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS METADATA;

-- 4. Internal Stages for CSV uploads
USE SCHEMA RAW;
CREATE STAGE IF NOT EXISTS OLIST_STAGE
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

CREATE STAGE IF NOT EXISTS SUPERSTORE_STAGE
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

-- 5. Grant Cortex access (run as ACCOUNTADMIN)
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SYSADMIN;
